# Generated by Django 5.2.4 on 2025-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('users', '0001_initial'),
  ]

  operations = [
    migrations.AddField(
      model_name='user',
      name='role',
      field=models.CharField(default='viewer', max_length=20),
    ),
  ]
