# Generated by Django 5.2.4 on 2025-08-03 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('flights', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='CrewMember',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=100)),
        ('role', models.CharField(choices=[('pilot', 'Pilot'), ('copilot', 'Co-Pilot'), ('attendant', 'Flight Attendant')], max_length=20)),
        ('assigned_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='flights.flight')),
      ],
    ),
  ]
