# Generated by Django 5.2.4 on 2025-08-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewmember',
            options={'ordering': ['name'], 'verbose_name': 'Crew Member', 'verbose_name_plural': 'Crew Members'},
        ),
    ]
