# Generated by Django 5.2.4 on 2025-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
